### ISSUE TITLE
glosnik nie dziala

### ISSUE THREAD

**Issue by puuska** [NitroFuN/device_xiaomi_ginkgo#1]
mikrofon tez
prosze naprawic

**Comment by puuska** [comment]
halo??????

**Comment by NitroFuN** [comment]
no i zajebiście

**Comment by puuska** [comment]
![image](https://user-images.githubusercontent.com/11046280/88219394-ce1b2180-cc61-11ea-9838-345121723987.png)
my phone look this after flash

**Comment by puuska** [comment]
you scam

**Comment by puuska** [comment]
report

**Comment by NitroFuN** [comment]
`/*
 * Your warranty is now void.
 *
 * I am not responsible for bricked devices, dead SD cards,
 * thermonuclear war, or you getting fired because the alarm app failed. Please
 * do some research if you have any concerns about features included in this ROM
 * before flashing it! YOU are choosing to make these modifications, and if
 * you point the finger at me for messing up your device, I will laugh at you.
 */`
